version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - vector-db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fatstack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

volumes:
  pgdata: