FROM python:3.11-slim

WORKDIR /app

COPY ./backend /app

RUN pip install --upgrade pip \
  && pip install "fastapi[all]" uvicorn psycopg2-binary qdrant-client sentence-transformers

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
